apiVersion: v1
kind: Secret
metadata:
  name: tap-gui-tls
  namespace: tap-gui
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIGwTCCBamgAwIBAgITUwAAAf79wDjUp0FOoQABAAAB/jANBgkqhkiG9w0BAQsF
    ADBPMRQwEgYKCZImiZPy...
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAucLD2AC8D9SdP+BidVpXYEZG/vrHh602rTfR0Q/h2SWXLrgt
    eOIL3KiIf1QoqqcvOF2t...
    -----END RSA PRIVATE KEY-----
