apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "your-private-registry-fqdn": {
          "username": "your-developer-user",
          "password": "your-developer-password"
        }
      }
    }
