apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tanzu-tap-repository
  namespace: tap-install
spec:
  fetch:
    imgpkgBundle:
      image: it-tkg-harbor.terasky.demo/tap/tap-packages:1.2.1